const mongoose = require('mongoose');

const urlSchema = new mongoose.Schema({
    urlCode: String, // This is the short part of the code generated by nanoid
    originalUrl: String, // Long url
    shortUrl: String, // The specified domain name plus the nanoid
    date:{ type: String, default: Date.now }
})

module.exports = mongoose.model('url', urlSchema);